### PR TITLE
lib: src: simulations: Added delay slider to Insertion Sort

### PR DESCRIPTION
**Pull request by akshansh2000**
Removed redundant statements as well

### CODE REVIEW

**Comment by yashlamba** [comment]
@akshansh2000 This looks cool, can you make the green lines grow from start to end as it right now just flashes? That would be cool...

**Comment by akshansh2000** [comment]
Yes, that's the next step.

I'll also do the the same for the blue bar i.e. comparisons starting from the beginning instead of directly pointing to the position.

**Comment by yashlamba** [comment]
> Yes, that's the next step.
> 
> I'll also do the the same for the blue bar i.e. comparisons starting from the beginning instead of directly pointing to the position.

So will you do it in the same PR? (Preferred) or should I complete the review?

**Comment by akshansh2000** [comment]
> So will you do it in the same PR? (Preferred) or should I complete the review?

Same PR, the only reason I opened a draft one. I'll mark it as ready for review once it's done. Sounds fine?

**Review by yashlamba — DISMISSED** [review]

**Review by yashlamba — APPROVED** [review]

**Pull request merged**
