### PR TITLE
'scrolling'

### PR DESCRIPTION
**Pull request by payal-98**
I add visible scrollbar in bottom navigator of Lissajous Pattern.
check if it is fine or not...?

### CODE REVIEW

**Comment by yashlamba** [comment]
I just read the code, good work on implementing this but isn't there a simpler way to implement this? This seems a bit overwhelming for such a task.

**Comment by payal-98** [comment]
@yashlamba  I found this logic only for always visible scroll bar..

**Comment by yashlamba** [comment]
@payal-98 You can try [this.](https://api.flutter.dev/flutter/material/Scrollbar-class.html)

**Comment by payal-98** [comment]
@yashlamba  Okk ..I made a PR using this..please check

**Pull request closed without merging**
