### PR TITLE
lib:simulations:Pigeonhole_Sort :PigeonHole Sort  implemented #166

### PR DESCRIPTION
**Pull request by mrmayurgithub**
@yashugarg I've added Pigeonsort algorithm simulation for solving the issue #166 , it works fine. 
I wanted to know that where can find an image for the algorithm similar to the images of bubble sort and insertion sort algorithm ?
After adding the image I think I make a final pull request.

### CODE REVIEW

**Comment by yashugarg** [comment]
hello @mrmayurgithub 
you'll have to take a screenshot of app while running the algorithm

**Comment by mrmayurgithub** [comment]
@yashugarg I've implemented the PigeonHole Sort Simulation.

**Comment by mrmayurgithub** [comment]
@yashugarg Can you please merge this pull request, or tell me if you want any changes .

**Comment by mrmayurgithub** [comment]
@yashugarg @yashlamba @sakshamarora1  Kindly review the PR and Merge it.

**Review by yashugarg — CHANGES_REQUESTED** [review]
Hello @mrmayurgithub 

I went through the simulation but it doesn't seem as informative as I thought it would. The elements just get changed to their expected value after sorting and doesn't really show the sorting process. Please think of a different approach, maybe display the pegionhole array first and then copy the elements.
And please increase the delay in the simulation
Also Please avoid commiting configuration files 

Thankyou!

**Pull request closed without merging**
