### PR TITLE
lib: src: Completely changed the category menu UI

### PR DESCRIPTION
**Pull request by akshansh2000**
@yashlamba, any modifications needed?

Tagging Issue: #2

### CODE REVIEW

**Comment by yashlamba** [comment]
Looks good but I'll say shorten the menu.dart file, can't we have some custom widget to be called on to add simulation cards. It'll shorten the code a lot and probably make it more understandable and readable. 
If you want to, you can take hints from #12.
More specifically https://github.com/cod-ed/simulate/blob/e7bf77317987a613999e13ed3a4273de84046ebf/lib/src/simulation_card.dart

**Comment by akshansh2000** [comment]
@yashlamba, I wasn't sure if we'll keep a similar background card/similar type of structure for each simulation, and so didn't make a common one. If you like this UI, we can proceed with putting the structure in a separate file.

**Comment by akshansh2000** [comment]
@yashlamba, I guess this is no longer needed?

**Comment by yashlamba** [comment]
> @yashlamba, I guess this is no longer needed?

I haven't started on the other UI yet, I like this as it looks but doubt it's practicality. It's your call, certainly if you'll make any new changes you can push here for menu.

**Pull request closed without merging**
