### PR TITLE
Readme file modified

### LINKED ISSUE #168: Modifying/Styling Readme.md file.
## Request ✨
Hello sir, I want to modify the readme.md file.

### Modifying it by adding 

1.)Adding shield batches in different colors for(at center-top below simulate image):
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars

2.) Sections
->Feature Section
->Dependencies Section
->Contributors Section
->Project Manager/Admin Section
->Changing Contributing section to Contributing Guidelines Section 

3.) Also, Should I add a section for steps to contribute with images -> Please let me know.

@yashugarg sir, please allow me to do so, by assigning me the issue under the GSSOC21 label & level label.

Thank you.

### PR DESCRIPTION
**Pull request by DOOMSTERR**
# Related Issue
* Fixed #168 

# Proposed Changes
Modified the Readme.md file as mentioned in issue #168, Please check the modifications done and let me know if anything needs to be changed again

### CODE REVIEW

**Comment by DOOMSTERR** [comment]
Please let me know if anything needs to be changed or modified.

**Review by yashugarg — CHANGES_REQUESTED** [review]
Hello @DOOMSTERR 

- [ ] The links for forks, stars, issues and PR badges are wrong
- [ ] Please rewrite the features to represent the application better
- [ ] I am not the only project maintainer to please remove that section
- [ ] Avoid using emoticons in the readme file

Thankyou

**Comment by DOOMSTERR** [comment]
Please check it again.
I have updated the file according to the changes mentioned by @yashugarg.

Also, I haven't touched the features section, after merging it others can also modify that section, or you guys can also do it.

**Comment by DOOMSTERR** [comment]
Hello, other than the 2nd Point everything is solved successfully, also 2nd point can be modified later by you guys.
Because you know the application better.

**Comment by DOOMSTERR** [comment]
If the changes did are ok please merge the pull request, as GSSOC is about to end.

**Pull request merged**
